apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aiprt-web
  namespace: aiprt
  description: aiprt Web App
  annotations:
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=aiprt"
    backstage.io/techdocs-ref: dir:.
  tags:
   - aiprt
   - dpd
   - demo
  links:
    - url: https://www.dpd.gov/
      title: DPD Home
      icon: language
spec:
  type: service
  lifecycle: production
  owner: aiprt-team
  system: aiprt-system
  consumesApis:
   - aiprt/aiprt-rest-service-6845e3ec